# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'R2D2Mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for R2D2Mobile
  pod 'FirebaseMessaging'

end
